FROM python:3.12-slim

WORKDIR /exhback

RUN set -eux && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        libpq5 && \
    rm -rf /var/lib/lists/* && \
    groupadd \
            --system \
        exhback && \
        useradd \
            --system \
        exhback \
            -g \
        exhback
